name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ hashFiles('**/package-lock.json') }}
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run type checks
      run: npx tsc -p tsconfig.json --noEmit
    - name: Create report directories
      run: |
        mkdir -p allure-results
        mkdir -p blob-report
        mkdir -p test-results
        chmod -R 777 allure-results blob-report test-results
    - name: Run Playwright tests
      env:
        HOME: /root
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        COOKIES_JSON: ${{ secrets.COOKIES_JSON }}
        LOCAL_STORAGE_JSON: ${{ secrets.LOCAL_STORAGE_JSON }}
        DOCKER_CONFIG: "/tmp/.docker" # Override Docker config location
      run: |
        xvfb-run npx playwright test --config=playwright.ci.config.ts --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
    - name: Upload blob report to GitHub Actions Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: blob-report-${{ matrix.shardIndex }}
        path: blob-report
        retention-days: 30
    - name: Upload Allure results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ matrix.shardIndex }}
        path: allure-results
        retention-days: 30

  merge-reports:
    # Merge reports after test, even if some shards have failed
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        path: all-blob-reports
        pattern: blob-report-*
        merge-multiple: true
    - name: Create report directories
      run: |
        mkdir -p playwright-report
        mkdir -p allure-results
        mkdir -p allure-report
    - name: Merge into HTML Report
      run: npx playwright merge-reports --reporter html ./all-blob-reports
    #- name: Setup Pages
    #  uses: actions/configure-pages@v5
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 30
    #- name: Copy Specific Files
    #  run: |
    #    mkdir cleaned-report
    #    cp playwright-report/index.html cleaned-report/
    #- name: Upload HTML report
    #  uses: actions/upload-artifact@v4
    #  with:
    #      name: github-pages
    #      path: cleaned-report
    #- name: Deploy to GitHub Pages
    #  id: deployment
    #  uses: actions/deploy-pages@v4
    - name: Download Allure results
      uses: actions/download-artifact@v4
      with:
        path: allure-results
        pattern: allure-results-*
        merge-multiple: true
    - name: Generate Allure report
      run: |
        npm install -g allure-commandline
        allure generate allure-results --clean -o allure-report
    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report--attempt-${{ github.run_attempt }}
        path: allure-report
        retention-days: 30
